### ISSUE TITLE
about metrics

### ISSUE THREAD

**Issue by ls8725** [compendius/libvirt_nova_exporter_py#1]
The existing indicators are a little short, can there be more?Not sure how to support other metrics

**Comment by compendius** [comment]
Hi,
This was designed to be a minimal exported with key Openstack Nova metrics for simplicity. Which metrics were you looking for?

**Comment by ls8725** [comment]
HI, Thank you for your reply. I am looking for some monitoring indicators for virtual machines, but I do not know whether they are supported or not. What I need to implement is an exporter that can export monitoring data of virtual machines on multiple cloud platforms

**Comment by compendius** [comment]
This is based around Openstack cloud as the code looks for Nova attributes in the libvirt XML-
 
`nova_name = str(char.find('oa:name', ns).text)
              for char1 in char.findall('oa:owner', ns):
                  nova_project = str(char1.find('oa:project', ns).text)`
                  
You could remove Nova references, fork this and read the python libvirt documentation https://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/ to find more metrics.

The best way to get lots of stats with one call would be to use the Go libvirt GetAllDomainStats() https://pkg.go.dev/github.com/libvirt/libvirt-go#Connect.GetAllDomainStats . You could then produce a binary with no local dependencies running on multiple clouds. 
I also have a Go exporter which you could fork and work on to achieve this - 

https://github.com/compendius/libvirt_nova_exporter

HTH

**Comment by ls8725** [comment]
I just read the literature you recommended. Due to my poor English level, I can only understand part of it. In these documents, I did not find a way to create multiple connections through a unified exporter. I hope to achieve this in one exporter. Pull monitoring data of virtual machines on multiple openstack platforms. Can the connector of go-libvirt support remote connection?

**Comment by compendius** [comment]
You can connect to libvirt in Openstack remotely via SSH (provided it is enabled in libvirt config) for example in python
```
  try:
     conn = libvirt.openReadOnly('qemu+ssh://heat-admin@' + hyp_host + '/system')
   except:
    raise ValueError('ERROR connecting to ' + hyp_host)
   domainID = `conn.listDomainsID()
    if len(domainID) != 0:
      for domainID in domainID:
         domain = conn.lookupByID(domainID)
```
You could then simplify and instead of writing an exporter you could use the Prometheus text file collector to expose metrics

https://github.com/prometheus/node_exporter#textfile-collector

For example (in bash) - 
https://www.robustperception.io/using-the-textfile-collector-from-a-shell-script

I would always recommend however running an exporter on each Openstack hypervisor if at all possible.

**Comment by ls8725** [comment]
I forgot to reply to you yesterday. Thank you very much for your answer. I currently choose another way to export data, which is to obtain data by requesting ceilometer. Although this method is inefficient, it does not require direct access to each node of openstack.
